import { Stock } from '../types/portfolio';

export const mockStocks: Stock[] = [
  {
    id: '1',
    particulars: 'Reliance Industries Ltd',
    symbol: 'RELIANCE',
    purchasePrice: 2200,
    quantity: 50,
    investment: 110000,
    portfolioPercentage: 22.5,
    exchange: 'NSE',
    cmp: 2350,
    presentValue: 117500,
    gainLoss: 7500,
    gainLossPercentage: 6.82,
    peRatio: 28.5,
    latestEarnings: 'Q3 FY24: ₹18,951 Cr',
    sector: 'Energy',
    lastUpdated: new Date(),
  },
  {
    id: '2',
    particulars: 'Tata Consultancy Services',
    symbol: 'TCS',
    purchasePrice: 3200,
    quantity: 30,
    investment: 96000,
    portfolioPercentage: 19.6,
    exchange: 'NSE',
    cmp: 3450,
    presentValue: 103500,
    gainLoss: 7500,
    gainLossPercentage: 7.81,
    peRatio: 24.2,
    latestEarnings: 'Q3 FY24: ₹11,735 Cr',
    sector: 'Technology',
    lastUpdated: new Date(),
  },
  {
    id: '3',
    particulars: 'HDFC Bank Ltd',
    symbol: 'HDFCBANK',
    purchasePrice: 1550,
    quantity: 40,
    investment: 62000,
    portfolioPercentage: 12.7,
    exchange: 'NSE',
    cmp: 1485,
    presentValue: 59400,
    gainLoss: -2600,
    gainLossPercentage: -4.19,
    peRatio: 18.7,
    latestEarnings: 'Q3 FY24: ₹16,512 Cr',
    sector: 'Financials',
    lastUpdated: new Date(),
  },
  {
    id: '4',
    particulars: 'Infosys Ltd',
    symbol: 'INFY',
    purchasePrice: 1400,
    quantity: 35,
    investment: 49000,
    portfolioPercentage: 10.0,
    exchange: 'NSE',
    cmp: 1520,
    presentValue: 53200,
    gainLoss: 4200,
    gainLossPercentage: 8.57,
    peRatio: 26.8,
    latestEarnings: 'Q3 FY24: ₹6,586 Cr',
    sector: 'Technology',
    lastUpdated: new Date(),
  },
  {
    id: '5',
    particulars: 'ITC Ltd',
    symbol: 'ITC',
    purchasePrice: 420,
    quantity: 100,
    investment: 42000,
    portfolioPercentage: 8.6,
    exchange: 'NSE',
    cmp: 445,
    presentValue: 44500,
    gainLoss: 2500,
    gainLossPercentage: 5.95,
    peRatio: 22.1,
    latestEarnings: 'Q3 FY24: ₹4,875 Cr',
    sector: 'Consumer Goods',
    lastUpdated: new Date(),
  },
  {
    id: '6',
    particulars: 'Bajaj Finance Ltd',
    symbol: 'BAJFINANCE',
    purchasePrice: 6800,
    quantity: 8,
    investment: 54400,
    portfolioPercentage: 11.1,
    exchange: 'NSE',
    cmp: 6950,
    presentValue: 55600,
    gainLoss: 1200,
    gainLossPercentage: 2.21,
    peRatio: 31.4,
    latestEarnings: 'Q3 FY24: ₹3,551 Cr',
    sector: 'Financials',
    lastUpdated: new Date(),
  },
  {
    id: '7',
    particulars: 'Asian Paints Ltd',
    symbol: 'ASIANPAINT',
    purchasePrice: 3100,
    quantity: 15,
    investment: 46500,
    portfolioPercentage: 9.5,
    exchange: 'NSE',
    cmp: 2980,
    presentValue: 44700,
    gainLoss: -1800,
    gainLossPercentage: -3.87,
    peRatio: 45.2,
    latestEarnings: 'Q3 FY24: ₹1,211 Cr',
    sector: 'Consumer Goods',
    lastUpdated: new Date(),
  },
  {
    id: '8',
    particulars: 'Maruti Suzuki India Ltd',
    symbol: 'MARUTI',
    purchasePrice: 9200,
    quantity: 6,
    investment: 55200,
    portfolioPercentage: 11.3,
    exchange: 'NSE',
    cmp: 9850,
    presentValue: 59100,
    gainLoss: 3900,
    gainLossPercentage: 7.07,
    peRatio: 21.8,
    latestEarnings: 'Q3 FY24: ₹3,727 Cr',
    sector: 'Automotive',
    lastUpdated: new Date(),
  },
];

// Function to simulate real-time price updates
export const getRandomPriceChange = (currentPrice: number): number => {
  const changePercent = (Math.random() - 0.5) * 0.04; // ±2% change
  return Math.round((currentPrice * (1 + changePercent)) * 100) / 100;
};

// Mock API delay simulation
export const simulateApiDelay = (ms: number = 500): Promise<void> => {
  return new Promise(resolve => setTimeout(resolve, ms));
};